classroom.building=Главный корпус
classroom.room_number=000
classroom.name=Аудитория общего пользования
classroom.area=30.0

responsible.fio=Не назначен
responsible.position=Лаборант
responsible.phone=000000
responsible.age=30
